### ISSUE TITLE
音视频通话失败

### ISSUE THREAD

**Issue by imndx** [wildfirechat/uni-h5-chat#2]
有如下报错：
```
index.987781ec.js:1 
RangeError: Maximum call stack size exceeded
    at s.get [as _events] (chunk-vendors.8908e445.js:50:7514)
    at s.emit (chunk-vendors.8908e445.js:50:85609)
    at e.value (index.987781ec.js:1:427289)
    at s.<anonymous> (index.987781ec.js:1:421854)
    at s.emit (chunk-vendors.8908e445.js:50:85934)
    at e.value (index.987781ec.js:1:427289)
    at s.<anonymous> (index.987781ec.js:1:421854)
    at s.emit (chunk-vendors.8908e445.js:50:85934)
    at e.value (index.987781ec.js:1:427289)
    at s.<anonymous> (index.987781ec.js:1:421854)
```

**Comment by imndx** [comment]
已解决
